import {ScanResult} from '../engine/types.js'

export function renderMarkdownReport(result: ScanResult): string {
  const lines: string[] = []

  lines.push('# Agentia Release Guardian')
  lines.push('')

  lines.push('## Release Summary')
  lines.push('')

  lines.push(`- **Repository:** \`${result.repository.root}\``)
  lines.push(`- **Branch:** \`${result.repository.branch}\``)
  lines.push(`- **Changed files:** ${result.changedFiles}`)
  lines.push(`- **Risk score:** ${result.riskScore}/100`)
  lines.push(`- **Risk level:** ${result.riskLevel}`)
  lines.push(`- **Release status:** **${result.releaseStatus}**`)
  lines.push('')

  lines.push('## Findings')
  lines.push('')

  if (result.findings.length === 0) {
    lines.push('No findings detected.')
    lines.push('')
  } else {
    lines.push('| Severity | ID | Finding | File | Score |')
    lines.push('|---|---|---|---|---:|')

    for (const finding of result.findings) {
      lines.push(
        `| ${finding.severity} | ${finding.id} | ${finding.title} | \`${finding.file}\` | ${finding.score} |`,
      )
    }

    lines.push('')

    for (const finding of result.findings) {
      lines.push(`### ${finding.id} — ${finding.title}`)
      lines.push('')
      lines.push(finding.description)
      lines.push('')

      if (finding.evidence && finding.evidence.length > 0) {
        lines.push('**Evidence:**')

        for (const evidence of finding.evidence) {
          lines.push(`- ${evidence}`)
        }

        lines.push('')
      }

      if (finding.recommendation) {
        lines.push(`**Recommendation:** ${finding.recommendation}`)
        lines.push('')
      }
    }
  }

  lines.push('## Policy Evaluation')
  lines.push('')

  lines.push(`- **Maximum risk score:** ${result.policy.maxRiskScore}`)
  lines.push(
    `- **Policy result:** ${
      result.policy.evaluation.passed ? 'PASS' : 'BLOCKED'
    }`,
  )
  lines.push('')

  if (result.policy.evaluation.violations.length > 0) {
    lines.push('### Policy Violations')
    lines.push('')

    for (const violation of result.policy.evaluation.violations) {
      lines.push(`- **${violation.rule}:** ${violation.message}`)

      if (violation.findings.length > 0) {
        lines.push(`  - Affected: ${violation.findings.join(', ')}`)
      }
    }

    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('Generated by Agentia Release Guardian.')

  return lines.join('\n')
}